<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="regression_files/libs/quarto-html/quarto.js"></script>
<script src="regression_files/libs/quarto-html/popper.min.js"></script>
<script src="regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="regression_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="regression_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="multivariate-regression" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-regression">Multivariate regression</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reminder
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>If using categorical predictors (for example, testing 2 x 2 factorial designs using regression), make sure that the IVs are <strong>effect coded</strong>, so that one level is -1 and the other is +1. This allows you to compare each group to the overall average of the sample, rather than to the reference category. It also makes interpretation of interactions easier. See <a href="recoding.qmd">Recoding variables</a> for a guide.</li>
<li>If testing moderation by a continuous variable, make sure all continuous variables involved in interactions have been mean centred. This reduces multicollinearity between the interaction and its constituent variables, and again, makes interpretation of interactions easier. See <a href="standardising.qmd">Mean centring and standardising</a> for a guide.</li>
</ol>
</div>
</div>
<p>I like to conduct multivariate regression analyses using the following code, using the <strong>base r</strong> functions + the apaTables package <span class="citation" data-cites="apaTables2026">[@apaTables2026]</span> to produce publication-ready tables.</p>
<p>In this example, we are testing a 2 x 2 factorial design, with one continuous moderator. The factors have been effect-coded (-1 and +1), and the continuous moderator has been mean-centred.</p>
<p>We must build three models representing each ‘block’ in hierarchical regression. The <strong>main effects</strong> are entered in Block 1, the <strong>two-way interactions</strong> are entered in Block 2, and the <strong>three-way interaction</strong> is entered in Block 3.</p>
<section id="understanding-the-regression-formula" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-regression-formula">Understanding the regression formula</h3>
<p>When specifying regression models in R, we use formula syntax that describes the relationship between variables.</p>
<p>The general formula is: the <strong>dependent variable</strong> is to the left of the <code>~</code> symbol and the <strong>predictor variables</strong> are to the right of this symbol. The <code>~</code> symbol can therefore be understood as “is predicted by” or “is explained by.”</p>
<p>Therefore the formula <code>DV ~ IV1 + IV2</code> can be read in plain English as “DV is predicted by IV1 and IV2.”</p>
<p>Additional predictors are separated by a <code>+</code> symbol. If you are examining the interaction between variables, you use the colon symbol <code>:</code>.</p>
<p>For example, the formula <code>DV ~ IV1:IV2</code> tests whether the effect of IV1 on DV depends on the level of IV2. Main effects and interactions must be added separately.</p>
<p>The asterisk symbol <code>*</code> is shorthand that automatically includes all main effects and interactions between variables. So, if you wanted to test a three-way interaction, the code <code>IV1 * IV2 * IV3</code> would automatically include the main effects of IV1, IV2, and IV3, all two-way interactions, and the three-way interaction. This expands to:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>DV <span class="sc">~</span> IV1 <span class="sc">+</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>     IV2 <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>     IV3 <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>     IV1<span class="sc">:</span>IV2 <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>     IV1<span class="sc">:</span>IV3 <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>     IV2<span class="sc">:</span>IV3 <span class="sc">+</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>     IV1<span class="sc">:</span>IV2<span class="sc">:</span>IV3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>If you are testing a hierarchical regression model where you need to enter the main effects and two-way interactions at a separate step from the three-way interaction, you will need to build separate models to do this. An example of this is provided below.</p>
<p>Finally, <code>I()</code> forces R to evaluate an arithmetic expression literally and use the result as a single predictor, rather than interpreting it as formula syntax. <code>I(IV1 * IV2)</code> creates one new numeric column equal to <code>IV1 × IV2</code> – that is, mathematically identical to the <code>IV1:IV2</code> interaction term, but stored and labelled as an ordinary product variable rather than a formula-level interaction.</p>
<ul>
<li>This is necessary for calculating the standardised betas in apa.reg.table(). To be clear, <code>I(IV1 * IV2)</code> will give the exact same coefficients (B), SEs, and p-values as <code>IV1:IV2</code> and <code>IV1*IV2</code>. The difference only matters once you pass the model to <code>apa.reg.table()</code>, because <code>apa.reg.table()</code> calculates the <strong>standardised beta</strong> for each predictor by re-fitting the model on standardised variables. To do this, it needs each interaction term to already exist in the data as an actual numeric column with a name it can parse (e.g.&nbsp;<code>I(IV1 * IV2)</code>). If you don’t include the interaction terms in I(), the table will still be produced, but you won’t get standardised betas or 95% confidence intervals for standardised betas.</li>
</ul>
</section>
<section id="block-1-main-effects" class="level3">
<h3 class="anchored" data-anchor-id="block-1-main-effects">Block 1: Main effects</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Block 1: Main effects</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>model_b1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV1 <span class="sc">+</span> IV2 <span class="sc">+</span> moderator_mc, dat)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_b1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DV ~ IV1 + IV2 + moderator_mc, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.2852  -2.7730   0.0283   2.5853  13.9785 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   50.0577     0.2313 216.409  &lt; 2e-16 ***
IV1            1.9341     0.2330   8.302 3.70e-15 ***
IV2            1.4399     0.2322   6.201 1.89e-09 ***
moderator_mc   1.8521     0.2358   7.856 7.40e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.005 on 296 degrees of freedom
Multiple R-squared:  0.3664,    Adjusted R-squared:   0.36 
F-statistic: 57.07 on 3 and 296 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>What this is doing:</strong></p>
<ul>
<li><p>This model estimates the direct effects of each predictor on the dependent variable.</p></li>
<li><p>DV is the dependent/outcome/criterion variable. IV1 and IV2 are effect-coded categorical predictors (where -1 = one level, +1 = the other level). moderator_mc is a continuous moderator that has been mean-centred.</p></li>
<li><p>All predictors are separated by <code>+</code>, meaning they are tested on average across all levels of the other variables (i.e., they are main effects).</p></li>
<li><p>As we can see from the output, the model is significant, <em>F</em>(3, 296) = 57.07, <em>p</em> &lt; .001 and explains 37% of the total variance in the DV. All main effects are significant.</p></li>
</ul>
</section>
<section id="block-2-two-way-interactions" class="level3">
<h3 class="anchored" data-anchor-id="block-2-two-way-interactions">Block 2: Two-way interactions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model_b2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV1 <span class="sc">+</span> IV2 <span class="sc">+</span> moderator_mc <span class="sc">+</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV1 <span class="sc">*</span> IV2) <span class="sc">+</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV1 <span class="sc">*</span> moderator_mc) <span class="sc">+</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV2 <span class="sc">*</span> moderator_mc), </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>               dat)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_b2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DV ~ IV1 + IV2 + moderator_mc + I(IV1 * IV2) + I(IV1 * 
    moderator_mc) + I(IV2 * moderator_mc), data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.4114 -2.4386  0.2454  2.3554  9.6023 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            49.9997     0.2085 239.859  &lt; 2e-16 ***
IV1                     1.9594     0.2077   9.432  &lt; 2e-16 ***
IV2                     1.4723     0.2071   7.109 8.95e-12 ***
moderator_mc            1.9893     0.2112   9.420  &lt; 2e-16 ***
I(IV1 * IV2)            1.1152     0.2085   5.349 1.79e-07 ***
I(IV1 * moderator_mc)   0.8425     0.2149   3.920  0.00011 ***
I(IV2 * moderator_mc)   1.1262     0.2159   5.217 3.45e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.57 on 293 degrees of freedom
Multiple R-squared:  0.5016,    Adjusted R-squared:  0.4914 
F-statistic: 49.15 on 6 and 293 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>What this is doing:</strong></p>
<ul>
<li><p>This model adds all possible two-way interactions between the predictors, in addition to the main effects from Block 1.</p></li>
<li><p>As explained above, because we want to produce a table with standardised betas, we have to include these interactions within the I() function.</p></li>
<li><p>By comparing Block 2 to Block 1, we can determine whether including these interactions explains additional variance in the dependent variable.</p></li>
<li><p>As we can see, the total model is again significant, <em>F</em>(6, 293) - 49.15, <em>p</em> &lt; .001 and explains 50% of the total variance in DV. All two-way interactions are significant.</p></li>
</ul>
</section>
<section id="block-3-three-way-interactions" class="level3">
<h3 class="anchored" data-anchor-id="block-3-three-way-interactions">Block 3: Three-way interactions</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model_b3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DV <span class="sc">~</span> IV1 <span class="sc">+</span> IV2 <span class="sc">+</span> moderator_mc <span class="sc">+</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV1 <span class="sc">*</span> IV2) <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV1 <span class="sc">*</span> moderator_mc) <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV2 <span class="sc">*</span> moderator_mc) <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">I</span>(IV1 <span class="sc">*</span> IV2 <span class="sc">*</span> moderator_mc), </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>               dat)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_b3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DV ~ IV1 + IV2 + moderator_mc + I(IV1 * IV2) + I(IV1 * 
    moderator_mc) + I(IV2 * moderator_mc) + I(IV1 * IV2 * moderator_mc), 
    data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.1197 -2.1623  0.2506  1.9471  8.1595 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  50.0429     0.1806 277.124  &lt; 2e-16 ***
IV1                           1.8054     0.1806   9.998  &lt; 2e-16 ***
IV2                           1.6807     0.1806   9.307  &lt; 2e-16 ***
moderator_mc                  1.6020     0.1870   8.567 6.24e-16 ***
I(IV1 * IV2)                  1.0981     0.1806   6.081 3.73e-09 ***
I(IV1 * moderator_mc)         1.0238     0.1870   5.475 9.44e-08 ***
I(IV2 * moderator_mc)         1.0835     0.1870   5.794 1.77e-08 ***
I(IV1 * IV2 * moderator_mc)   1.8575     0.1870   9.933  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.092 on 292 degrees of freedom
Multiple R-squared:  0.6275,    Adjusted R-squared:  0.6185 
F-statistic: 70.26 on 7 and 292 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>What this is doing:</strong></p>
<ul>
<li>As we can see from the output, the total model is again significant, <em>F</em>(7, 292) = 70.26, <em>p</em> &lt; .001 and explains 63% of the total variance in DV. The three-way interaction is also significant.</li>
</ul>
</section>
<section id="producing-an-apa-formatted-regression-table" class="level3">
<h3 class="anchored" data-anchor-id="producing-an-apa-formatted-regression-table">Producing an APA-formatted regression table</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tab_model <span class="ot">&lt;-</span> <span class="fu">apa.reg.table</span>(model_b1, model_b2, model_b3)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>tab_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Regression results using DV as the criterion
 

                   Predictor       b       b_95%_CI beta  beta_95%_CI sr2
                 (Intercept) 50.06** [49.60, 50.51]                      
                         IV1  1.93**   [1.48, 2.39] 0.39 [0.30, 0.48] .15
                         IV2  1.44**   [0.98, 1.90] 0.29 [0.20, 0.38] .08
                moderator_mc  1.85**   [1.39, 2.32] 0.37 [0.27, 0.46] .13
                                                                         
                                                                         
                                                                         
                 (Intercept) 50.00** [49.59, 50.41]                      
                         IV1  1.96**   [1.55, 2.37] 0.39 [0.31, 0.47] .15
                         IV2  1.47**   [1.06, 1.88] 0.29 [0.21, 0.38] .09
                moderator_mc  1.99**   [1.57, 2.40] 0.39 [0.31, 0.48] .15
                I(IV1 * IV2)  1.12**   [0.70, 1.53] 0.22 [0.14, 0.30] .05
       I(IV1 * moderator_mc)  0.84**   [0.42, 1.27] 0.17 [0.08, 0.25] .03
       I(IV2 * moderator_mc)  1.13**   [0.70, 1.55] 0.22 [0.14, 0.31] .05
                                                                         
                                                                         
                                                                         
                 (Intercept) 50.04** [49.69, 50.40]                      
                         IV1  1.81**   [1.45, 2.16] 0.36 [0.29, 0.43] .13
                         IV2  1.68**   [1.33, 2.04] 0.34 [0.27, 0.41] .11
                moderator_mc  1.60**   [1.23, 1.97] 0.32 [0.24, 0.39] .09
                I(IV1 * IV2)  1.10**   [0.74, 1.45] 0.22 [0.15, 0.29] .05
       I(IV1 * moderator_mc)  1.02**   [0.66, 1.39] 0.20 [0.13, 0.27] .04
       I(IV2 * moderator_mc)  1.08**   [0.72, 1.45] 0.21 [0.14, 0.29] .04
 I(IV1 * IV2 * moderator_mc)  1.86**   [1.49, 2.23] 0.37 [0.29, 0.44] .13
                                                                         
                                                                         
                                                                         
 sr2_95%_CI     r             Fit        Difference
                                                   
 [.08, .21] .37**                                  
 [.03, .13] .33**                                  
 [.07, .19] .35**                                  
                      R2 = .366**                  
                  95% CI[.28,.44]                  
                                                   
                                                   
 [.09, .21] .37**                                  
 [.04, .13] .33**                                  
 [.09, .21] .35**                                  
 [.01, .08]                                        
 [.00, .05]                                        
 [.01, .08]                                        
                      R2 = .502** Delta R2 = .135**
                  95% CI[.42,.56]  95% CI[.08, .19]
                                                   
                                                   
 [.08, .18] .37**                                  
 [.06, .16] .33**                                  
 [.05, .14] .35**                                  
 [.02, .08]                                        
 [.01, .07]                                        
 [.01, .07]                                        
 [.08, .18]                                        
                      R2 = .627** Delta R2 = .126**
                  95% CI[.56,.67]  95% CI[.08, .18]
                                                   

Note. A significant b-weight indicates the beta-weight and semi-partial correlation are also significant.
b represents unstandardized regression weights. beta indicates the standardized regression weights. 
sr2 represents the semi-partial correlation squared. r represents the zero-order correlation.
Square brackets are used to enclose the lower and upper limits of a confidence interval.
* indicates p &lt; .05. ** indicates p &lt; .01.
 </code></pre>
</div>
</div>
<p><strong>What this is doing:</strong></p>
<ul>
<li><p>The <code>apa.reg.table()</code> function from <strong>apaTables</strong> package <span class="citation" data-cites="apaTables2026">[@apaTables2026]</span> combines the results from all three regression models into a single, publication-ready table. This means you do not have to worry about small errors and inconsistencies when copying over values – whoopee!</p></li>
<li><p>The table includes regression coefficients (B), standard errors, standardised coefficients (β), 95% confidence intervals, model R² values, changes in R² across blocks, and significance tests for individual predictors.</p></li>
<li><p>As we can see from the delta R² values, each model was a significant improvement on the one before.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>